---
match:
  distribution: '/CGI-Application-Framework-\d'
pl:
  expect:
    - '\QInstall examples'
    - "\n"
    - '\Qroot (pick a number or type a path)'
    - "\n"
    - '\Qframwork-root'
    - "\n"
    - '\Qexamples-path'
    - "\n"
    - '\Qexamples-url'
    - "\n"
    - '\Qcgi-bin-path'
    - "\n"
    - '\Qcgi-bin-url'
    - "\n"
    - '\QExamples user'
    - "\n"
    - '\QExamples group'
    - "\n"
    - '\QWeb server user'
    - "\n"
    - '\QWeb server group'
    - "\n"
    - '\QIs this configuration correct?'
    - "\n"
