---
match:
  distribution: '/Class-Data-ConfigHash-0\.00002\.'
  perlconfig:
    version: '^5\.41\.(3|4|5)$'
depends:
  configure_requires:
    Test::More: 0
pl:
  commandline: 'rm -rf inc/Test/More.pm; $PERL Makefile.PL'
# https://rt.cpan.org/Ticket/Display.html?id=156074
# not problematic anymore with perl 5.41.6+
